apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secertName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubectlapply.com
  dnsNames:
    - kubectlapply.com
    - www.kubectlapply.com
  acme:
    config:
      - http01:
          imgressClass: nginx
        domains:
          - kubectlapply.com
          - www.kubectlapply.com
